#!/usr/bin/env python3
"""Mechanical check for an as-built document, before any reader sees it.

WHY THIS EXISTS
  A reviewer's attention is the scarcest thing in this process. Everything a machine
  can catch should be caught before the reviewer opens the file, or the review gets
  spent on arithmetic and template residue and the real findings are the ones that
  survive.

  So this script owns: the section map, leftover placeholders, missing evidence
  tags, counts that disagree with each other, hedging language, evaluation that
  crept into a document that is not allowed to evaluate, and empty cells. What it
  cannot own is whether the content is TRUE -- that is the auditor's work
  (references/denetci.md) and this script passing means nothing about it.

WHAT IT CHECKS
  A  section map        0-11, in order, none missing, none duplicated
  B  template residue   << >>, FILL:, TODO, HTML comment blocks
  C  evidence tags      a table with no [V]/[I]/[S]/[U] anywhere above it
  D  count agreement    inventory TOTAL vs the detail rows beneath it
  E  hedging            probably / apparently / it seems / untagged may
  F  evaluation         risk, recommendation, should, technical debt, Clean Core
  G  empty cells        a table body cell left blank instead of given a reason
  H  automation trace   "generated by", ISO timestamps in prose, model voice
  I  forbidden sections a heading the standard removed, back again

  Headings are matched by NUMBER, not by English title: the delivery language is a
  project decision and a Turkish document keeps the numbering and the tags.

USAGE
  py scripts/kontrol.py as-built/ALM-TS-FI-007_ZFI000_v1.0.md
  py scripts/kontrol.py as-built/*.md

EXIT
  0 clean · 1 blocker present · 2 warnings only
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# The console on a Turkish Windows machine is cp1254. Anything printed that is
# not plain ASCII kills the process there -- including text this file never sees
# in its own source, because a Turkish path or object name arrives through a
# variable. The work is finished by then, so the output lands on disk and the
# consultant still reads a traceback and reports the tool as broken.
# See scripts/test_skill_scripts.py for the three times this was found and
# locally fixed before it was made an invariant.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

TAGS = re.compile(r"\[(?:V|I|S|U)\]")
HEADING = re.compile(r"^#{1,2}\s+(\d+)\.\s")
TABLE_SEP = re.compile(r"^\|[\s:\-|]+\|$")

RESIDUE = [
    (re.compile(r"<<|>>"), "sablon yer tutucu (<< >>)"),
    (re.compile(r"\bFILL:", re.I), "FILL: isareti"),
    (re.compile(r"\bTODO\b", re.I), "TODO"),
    (re.compile(r"<!--"), "HTML yorum blogu"),
]

# Hedging. The rule is hard because the whole document is an evidence claim: a
# sentence that hedges is a sentence with no tag behind it.
HEDGE = [
    (re.compile(r"\bprobably\b", re.I), "probably"),
    (re.compile(r"\bapparently\b", re.I), "apparently"),
    (re.compile(r"\bpresumably\b", re.I), "presumably"),
    (re.compile(r"\bit seems\b", re.I), "it seems"),
    (re.compile(r"\bmuhtemelen\b", re.I), "muhtemelen"),
    (re.compile(r"\bg[oö]r[uü]n[uü][sş]e g[oö]re\b", re.I), "gorunuse gore"),
    (re.compile(r"\bsan[iı]r[iı]m\b", re.I), "sanirim"),
    (re.compile(r"standard SAP behaviou?r", re.I), "standard SAP behaviour (referanssiz olmasin)"),
]

# Evaluation. Warnings, not blockers: a package genuinely called ZRISK exists, and a
# script that refuses the document over its name is a script people stop running.
EVALUATION = [
    (re.compile(r"\brisk\b", re.I), "risk"),
    (re.compile(r"\bshould be\b", re.I), "should be"),
    (re.compile(r"\brecommend", re.I), "recommend"),
    (re.compile(r"\brefactor", re.I), "refactor"),
    (re.compile(r"\btechnical debt\b", re.I), "technical debt"),
    (re.compile(r"\bclean core\b", re.I), "clean core"),
    (re.compile(r"\bbest practice\b", re.I), "best practice"),
    (re.compile(r"\btest (?:case|scenario)\b", re.I), "test scenario"),
    (re.compile(r"\bimproved?\b", re.I), "improve"),
]

# The same ideas as headings. A heading is a decision, not a stray word, so these
# are blockers.
FORBIDDEN_SECTION = re.compile(
    r"^#{1,3}.*\b(risk register|risk log|test (?:cases|scenarios)|technical debt|"
    r"quality (?:assessment|evaluation|scoring)|clean core|orphan objects|"
    r"known limitations|recommendations)\b", re.I)

AUTOMATION = [
    (re.compile(r"\bgenerated (?:by|with|using)\b", re.I), "'generated by'"),
    (re.compile(r"\bas an? (?:AI|language model)\b", re.I), "model sesi"),
    (re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}"), "ISO zaman damgasi"),
    (re.compile(r"\bI (?:have )?analy[sz]ed\b", re.I), "birinci tekil sahis"),
]


class Finding:
    def __init__(self, level: str, rule: str, line: int, text: str):
        self.level, self.rule, self.line, self.text = level, rule, line, text

    def __str__(self) -> str:
        where = f"satir {self.line}" if self.line else "-"
        return f"  {self.level:<7} {self.rule}  {where}  {self.text}"


def strip_fences(lines: list[str]) -> list[bool]:
    """True for lines inside a fenced code block.

    Language rules do not apply to quoted ABAP: a source excerpt may legitimately
    contain the word `risk`, and flagging it teaches people to ignore the output.
    """
    out, fence = [], False
    for ln in lines:
        if ln.lstrip().startswith("```"):
            fence = not fence
            out.append(True)
            continue
        out.append(fence)
    return out


def section_of(lines: list[str]) -> list[int]:
    """Top-level section number in force at each line; -1 before section 0.

    Rules C and the [I] check apply to sections 1-10 only. Section 0 is document
    control -- a version history is a fact about the DOCUMENT, and demanding a
    source reference for it teaches people that the tag means nothing. Section 11
    is apparatus: a glossary defines words and Annex C is the method statement.
    Content lives in between, and that is where provenance is owed.

    Learned from the first real document rather than reasoned in advance: the
    check fired five times, and all five were section 0 or 11.
    """
    out, cur = [], -1
    for ln in lines:
        m = HEADING.match(ln)
        if m and ln.startswith("# "):
            cur = int(m.group(1))
        out.append(cur)
    return out


def tables(lines: list[str]) -> list[tuple[int, int]]:
    """(header_line_index, last_body_line_index) for each markdown table."""
    found, i = [], 0
    while i < len(lines):
        if TABLE_SEP.match(lines[i].strip()) and i and lines[i - 1].lstrip().startswith("|"):
            start = i - 1
            j = i + 1
            while j < len(lines) and lines[j].lstrip().startswith("|"):
                j += 1
            found.append((start, j - 1))
            i = j
        else:
            i += 1
    return found


def check_sections(lines: list[str], f: list) -> None:
    nums = [(i, int(m.group(1))) for i, ln in enumerate(lines)
            if (m := HEADING.match(ln)) and ln.startswith("# ")]
    seen = [n for _, n in nums]
    if not seen:
        f.append(Finding("BLOCKER", "A", 0, "numarali ust bolum bulunamadi"))
        return
    for want in range(12):
        if want not in seen:
            f.append(Finding("BLOCKER", "A", 0, f"bolum {want} yok -- silinmez, "
                                                "gerekcesiyle kapatilir"))
    for n in sorted(set(seen)):
        if seen.count(n) > 1:
            f.append(Finding("BLOCKER", "A", 0, f"bolum {n} {seen.count(n)} kez"))
        if n > 11:
            f.append(Finding("BLOCKER", "A", 0, f"haritada olmayan bolum {n}"))
    ordered = [n for n in seen if n <= 11]
    if ordered != sorted(ordered):
        f.append(Finding("BLOCKER", "A", 0, f"bolum sirasi kaymis: {ordered}"))


def check_tables(lines: list[str], f: list) -> None:
    sec = section_of(lines)
    for start, end in tables(lines):
        # A tag anywhere in the six lines above the table, or in the table itself.
        window = "\n".join(lines[max(0, start - 6):end + 1])
        if 1 <= sec[start] <= 10 and not TAGS.search(window):
            f.append(Finding("BLOCKER", "C", start + 1,
                             "tablonun kanit etiketi yok ([V]/[I]/[S]/[U])"))
        ncols = lines[start].count("|") - 1
        for i in range(start + 2, end + 1):
            cells = [c.strip() for c in lines[i].strip().strip("|").split("|")]
            if len(cells) == ncols and any(c == "" for c in cells):
                f.append(Finding("UYARI", "G", i + 1,
                                 "bos hucre -- tire degil, gerekce yazilir"))


def check_counts(lines: list[str], f: list) -> None:
    total, total_line = None, 0
    for i, ln in enumerate(lines):
        if re.match(r"^\|\s*\*\*TOTAL\*\*", ln, re.I) or re.match(r"^\|\s*TOTAL\b", ln, re.I):
            nums = re.findall(r"\d+", ln)
            if nums:
                total, total_line = int(nums[-1]), i + 1
    if total is None:
        f.append(Finding("UYARI", "D", 0, "envanter TOPLAM satiri bulunamadi -- "
                                          "sayim tutarliligi kontrol edilemedi"))
        return
    # The detail table is the FIRST table after the summary, because envanter.py
    # emits the two together and the writer pastes them together. Taking the widest
    # table instead -- the first attempt -- compared the inventory total against
    # Annex C's method table on the first real document, and reported a document
    # that was right as broken. A check that cries wolf is worse than no check.
    nxt = next(((s, e - s - 1) for s, e in tables(lines) if s + 1 > total_line), None)
    if nxt is None:
        f.append(Finding("UYARI", "D", total_line,
                         "TOPLAM var ama detay tablosu yok"))
        return
    if nxt[1] != total:
        f.append(Finding("BLOCKER", "D", total_line,
                         f"envanter TOPLAM {total}, detay tablosu {nxt[1]} satir"))


def check_language(lines: list[str], fenced: list[bool], f: list) -> None:
    for i, ln in enumerate(lines):
        if fenced[i]:
            continue
        for pat, label in RESIDUE:
            if pat.search(ln):
                f.append(Finding("BLOCKER", "B", i + 1, f"kalinti: {label}"))
        for pat, label in HEDGE:
            if pat.search(ln):
                f.append(Finding("BLOCKER", "E", i + 1, f"yasakli ifade: {label}"))
        for pat, label in AUTOMATION:
            if pat.search(ln):
                f.append(Finding("BLOCKER", "H", i + 1, f"otomasyon izi: {label}"))
        if FORBIDDEN_SECTION.match(ln):
            f.append(Finding("BLOCKER", "I", i + 1,
                             f"standarttan cikarilmis bolum geri gelmis: {ln.strip()[:60]}"))
        for pat, label in EVALUATION:
            if pat.search(ln) and not FORBIDDEN_SECTION.match(ln):
                f.append(Finding("UYARI", "F", i + 1,
                                 f"degerlendirme olabilir: {label} -- standart bolum 4"))
    # An [I] with no reasoning after it is a claim wearing a tag. Only a reader can
    # tell whether the reasoning actually SUPPORTS the claim, so this stays a
    # warning: a script that guesses at that is a script people switch off.
    # Fenced lines are blanked rather than dropped so the line numbers stay true.
    # Sections 1-10 only, for the same reason as the table rule -- and for one more:
    # section 0.4 carries the LEGEND of the four tags, so an unrestricted scan
    # reported the sentence that explains [I] as an [I] with no reasoning.
    reason = re.compile(r"^[\s`]*(?:[-:,(]|—|–|because\b|since\b|"
                        r"c[uü]nk[uü]\b|no\b|it\b|the\b|there\b)", re.I)
    sec = section_of(lines)
    text = "\n".join("" if fenced[i] else ln for i, ln in enumerate(lines))
    for m in re.finditer(r"\[I\]", text):
        line_no = text[:m.start()].count("\n")
        if not (1 <= sec[min(line_no, len(sec) - 1)] <= 10):
            continue
        if not reason.match(text[m.end():m.end() + 200]):
            f.append(Finding("UYARI", "C", line_no + 1,
                             "[I] var ama gerekce cumlesi gorunmuyor"))


def check(path: Path) -> list:
    lines = path.read_text(encoding="utf-8").splitlines()
    fenced = strip_fences(lines)
    f: list[Finding] = []
    check_sections(lines, f)
    check_tables(lines, f)
    check_counts(lines, f)
    check_language(lines, fenced, f)
    return f


def main() -> int:
    ap = argparse.ArgumentParser(description="as-built dokuman mekanik kontrolu")
    ap.add_argument("paths", nargs="+")
    a = ap.parse_args()

    worst = 0
    for raw in a.paths:
        p = Path(raw)
        if not p.is_file():
            print(f"bulunamadi: {p}")
            worst = max(worst, 1)
            continue
        f = check(p)
        blockers = [x for x in f if x.level == "BLOCKER"]
        warns = [x for x in f if x.level == "UYARI"]
        print(f"\n{p.name}")
        if not f:
            print("  TEMIZ")
            continue
        for x in sorted(f, key=lambda x: (x.level != "BLOCKER", x.line)):
            print(x)
        print(f"  -> {len(blockers)} BLOCKER, {len(warns)} UYARI")
        worst = max(worst, 1 if blockers else 2)

    if worst == 0:
        print("\nPASS -- mekanik kontrol temiz. Sirada bagimsiz denetim "
              "(references/denetci.md).")
    elif worst == 2:
        print("\nSadece uyari var. Her birine BAK -- bir kismi dogru olabilir, "
              "ama bakmadan gecme.")
    else:
        print("\nBLOCKER var. Denetime gonderme.")
    return worst


if __name__ == "__main__":
    sys.exit(main())
