"""Simplification Item Check XLSX -> list[SICheckFinding].

`/SDF/RC_START_CHECK` runs the Simplification Item Consistency Checks against the
customer's own system and reports, per item, whether it is relevant and whether
anything blocks the conversion. The consultant exports that result to Excel and
drops it in; nothing here touches SAP.

Why this is header-driven rather than positional
------------------------------------------------
The other XLSX ingester in this skill (readiness.py) can take row 5 as the header
row, because SAP Readiness Check tiles are generated by one exporter with one
layout. SI Check output is not: the column set differs by SAP_BASIS release, the
labels differ by logon language, and an export from the ALV grid does not look
like one from the report's own download. Hard-coding a position would produce a
file that parses into confident nonsense.

So: find the header row by recognising it, map each column through an alias
table, and if the two columns this record cannot exist without are not there,
RAISE and print every header that was seen. A schema this ingester does not know
is a fact worth reporting, not a row to skip -- the message is what tells the
next person which alias to add, and the first real export from a customer system
will do exactly that.

Everything unmapped is kept anyway: `status_raw` carries the cell as written, so
a value that could not be normalised survives into the report instead of being
flattened to "unknown".
"""

from __future__ import annotations

import re
from pathlib import Path

from openpyxl import load_workbook

from scripts.schemas import SchemaUnknown, SICheckFinding

# Column aliases, normalised (lowercased, non-alphanumerics collapsed). Turkish
# spellings are here because the export carries the logon language, and this kit
# is used from Turkish systems more often than not.
#
# THIS TABLE IS A STARTING POINT. It was written from the shape SI Check is
# documented to produce, not from a customer's file -- the first real export is
# expected to add to it, and the SchemaUnknown message below is how it says so.
_ALIASES: dict[str, tuple[str, ...]] = {
    "item_id": ("simplificationitem", "itemid", "siitem", "item", "checkid",
                "simplificationitemid", "basitlestirmekalemi", "kalem"),
    "title": ("title", "description", "itemtitle", "shorttext", "text",
              "baslik", "aciklama"),
    "status": ("status", "result", "checkresult", "severity", "messagetype",
               "type", "durum", "sonuc", "mesajtipi"),
    "message": ("message", "messagetext", "detail", "details", "longtext",
                "mesaj", "aciklamametni"),
    "sap_note_number": ("note", "sapnote", "notenumber", "sapnotenumber",
                        "notnumarasi", "sapnotu"),
    "affected_count": ("affectedobjects", "count", "objects", "numberofobjects",
                       "hits", "etkilenennesne", "adet", "sayi"),
    "area": ("area", "application", "applicationcomponent", "component",
             "responsible", "alan", "bilesen"),
}

# What a status cell can say. SAP writes the letter on one release, the word on
# another, and the traffic-light colour name in the Fiori export.
_STATUS: dict[str, str] = {
    "e": "error", "error": "error", "red": "error", "failed": "error",
    "hata": "error", "kirmizi": "error",
    "w": "warning", "warning": "warning", "yellow": "warning",
    "uyari": "warning", "sari": "warning",
    "i": "info", "info": "info", "information": "info", "bilgi": "info",
    "s": "ok", "success": "ok", "green": "ok", "ok": "ok", "passed": "ok",
    "basarili": "ok", "yesil": "ok",
    "notrelevant": "not-relevant", "irrelevant": "not-relevant",
    "na": "not-relevant", "ilgisiz": "not-relevant", "gecerlidegil": "not-relevant",
}

# The two columns a finding cannot exist without. A row with no item is not
# about anything; a row with no status does not say whether it matters.
_REQUIRED = ("item_id", "status")

# How far down to look for the header row. SI Check exports carry a banner of a
# few rows; twenty is generous and still bounded, so a file of the wrong kind
# fails fast rather than scanning a hundred thousand rows for a header it will
# never find.
_HEADER_SCAN_ROWS = 20


# Turkish letters folded to ASCII BEFORE the strip below. Without this the strip
# deletes them outright and every Turkish alias in the tables above is dead while
# looking perfectly written -- the word for "warning" lost its final letter and
# stopped matching, which is how this was found.
#
# U+0131 (dotless i) is the one that bites: it is ALREADY lowercase, so .lower()
# leaves it alone and [^a-z0-9] then removes it. U+0130 (dotted capital I) is the
# mirror image and lowercases to a two-codepoint sequence, so it is folded too.
_FOLD = str.maketrans({
    # ruff flags U+0131 as confusable with ASCII i, which is exactly the point:
    # this table is where the two are deliberately made the same. Silenced here
    # and nowhere else.
    "ı": "i",  # noqa: RUF001
    "İ": "i", "ş": "s", "Ş": "s", "ğ": "g", "Ğ": "g",
    "ü": "u", "Ü": "u", "ö": "o", "Ö": "o", "ç": "c", "Ç": "c",
})


def _norm(value: object) -> str:
    if value is None:
        return ""
    return re.sub(r"[^a-z0-9]", "", str(value).translate(_FOLD).lower())


def _map_headers(row: tuple[object, ...]) -> dict[str, int]:
    """Column index per field, for the fields this row's headers name.

    Exact matches are taken across the WHOLE row before any containment match is
    considered. Otherwise a sheet carrying both "Status" and "Status Description"
    could bind `status` to whichever came first, and a sheet carrying "Note" and
    "Note Text" could bind the number field to the text.
    """
    keys = [(idx, _norm(cell)) for idx, cell in enumerate(row)]
    found: dict[str, int] = {}
    taken: set[int] = set()

    for field, aliases in _ALIASES.items():
        for idx, key in keys:
            if key and idx not in taken and key in aliases:
                found[field] = idx
                taken.add(idx)
                break

    for field, aliases in _ALIASES.items():
        if field in found:
            continue
        for idx, key in keys:
            if key and idx not in taken and any(a in key for a in aliases):
                found[field] = idx
                taken.add(idx)
                break
    return found


def _int_or_none(value: object) -> int | None:
    if value is None:
        return None
    digits = re.sub(r"[^0-9]", "", str(value))
    return int(digits) if digits else None


class SICheckIngester:
    """Parse an SI Check XLSX export and return validated findings."""

    def load_dir(self, dir_path: Path) -> list[SICheckFinding]:
        """Every .xlsx in the folder. Missing folder is not an error -- the
        input is optional and the deliverables degrade to saying so."""
        if not dir_path.is_dir():
            return []
        out: list[SICheckFinding] = []
        for xlsx in sorted(dir_path.glob("*.xlsx")):
            out.extend(self.load(xlsx))
        return out

    def load(self, xlsx: Path) -> list[SICheckFinding]:
        wb = load_workbook(xlsx, read_only=True, data_only=True)
        findings: list[SICheckFinding] = []
        seen_headers: list[str] = []
        header_found = False

        for ws in wb.worksheets:
            rows = ws.iter_rows(values_only=True)
            cols: dict[str, int] = {}
            for i, row in enumerate(rows, start=1):
                if i > _HEADER_SCAN_ROWS:
                    break
                candidate = _map_headers(row)
                if all(f in candidate for f in _REQUIRED):
                    cols = candidate
                    header_found = True
                    break
                # Kept for the error message: these are the strings someone will
                # read to work out which alias is missing.
                seen_headers.extend(str(c) for c in row if c is not None)
            if not cols:
                continue
            # `rows` is a generator and the header row is already consumed, so
            # this picks up at the first data row.
            for row in rows:
                if all(c is None for c in row):
                    continue
                findings.append(self._row(row, cols))

        if not header_found:
            # A sheet this ingester cannot read is a fact worth reporting rather
            # than an empty list to shrug at: an SI Check export that silently
            # contributed nothing looks exactly like a conversion with no
            # blocking items, which is the most dangerous wrong answer here.
            raise SchemaUnknown(
                source=str(xlsx),
                unknown_root=(
                    "no header row naming both an item and a status. Headers seen: "
                    + (", ".join(list(dict.fromkeys(seen_headers))[:40]) or "(none)")
                    + " -- add the right spelling to _ALIASES in "
                      "scripts/ingesters/si_check.py"),
            )
        return findings

    @staticmethod
    def _row(row: tuple[object, ...], cols: dict[str, int]) -> SICheckFinding:
        def cell(field: str) -> object:
            idx = cols.get(field)
            return row[idx] if idx is not None and idx < len(row) else None

        raw_status = cell("status")
        status = _STATUS.get(_norm(raw_status), "unknown")

        return SICheckFinding(
            item_id=str(cell("item_id") or "").strip() or "(unnamed)",
            title=str(cell("title") or "").strip(),
            status=status,                                    # type: ignore[arg-type]
            status_raw=str(raw_status or "").strip(),
            message=str(cell("message") or "").strip(),
            sap_note_number=_int_or_none(cell("sap_note_number")),
            affected_count=_int_or_none(cell("affected_count")),
            area=str(cell("area") or "").strip(),
        )
